branch-defaults:
  master:
    environment: udagram-api-env
    group_suffix: null
deploy:
  artifact: udagram-api/www/Archive.zip
environment-defaults:
  udagram-api-env:
    branch: null
    repository: null
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
